apiVersion: v1
kind: Pod
metadata:
   name: falcon-website-pod
spec:
   containers:
   - name: falcon-website-01
     image: drcrane/falcon-website:2-b47a015
     env:
     - name: PORT
       value: "8080"
     ports:
     - containerPort: 8080

